#pragma once

typedef enum class collide_bit
{

	BALL = 0x01,
	PADDLE = 0x01 << 1,
	BRICK = 0x01 << 2,
	BOTTOM = 0x01 << 3,
	WALL = 0x01 << 4,
	SHATTER = 0x01 << 5,
	BONUS_FRUIT = 0x01 << 6,
	BONUS_BALL = 0x01 << 7,
	BONUS_BAR_UP = 0x01 << 8,
	BONUS_BAR_DOWN = 0x01 << 9,
	BONUS_SPEED_UP = 0x01 << 10,
	BONUS_SPEED_DOWN = 0x01 << 11,
	BONUS_QUESTION = 0x01 << 12,
	BONUS_EXCALMATION = 0x01 << 13,
	BONUS_BAD = 0x01 << 14,

}COLLIDE_BIT;

typedef enum class collide_type
{
	BALL_WALL = 0,
	BALL_BOTTOM,
	BALL_BRICK,
	BALL_PADDLE,

	PADDLE_FRUIT,
	PADDLE_BALL_UP,
	PADDLE_UP,
	PADDLE_DOWN,
	PADDLE_SPEED_UP,
	PADDLE_SPEED_DOWN,
	PADDLE_QUESTION,
	PADDLE_EXCALMATION,
	PADDLE_BAD,
	
	PADDLE_BONUS,
	BONUS_BOTTOM,
	UNKNOWN

}COLLIDE_TYPE;